parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Client\AuthClient:
        arguments:
            $authBaseUrl: '%env(AUTH_SERVICE_URL)%'
            $projectBaseUrl: '%env(PROJECT_SERVICE_URL)%'
            $jwtSecret: '%env(JWT_SECRET)%'

    App\Client\ProjectClient:
        arguments:
            $baseUrl: '%env(PROJECT_SERVICE_URL)%'
