package edu.ehei.gitdock.gitdocknotification.enums;

public enum NotificationType {
    TYPE_USER_REGISTERED,
    TYPE_PASSWORD_RESET_REQUESTED,
    TYPE_PROJECT_INVITATION,
    TYPE_PROJECT_CREATED,
    TYPE_PROJECT_CREATION_FAILED,
    TYPE_NEW_COMMIT,
    TYPE_SYNC_DELAYED,
    TYPE_SYNC_COMPLETE,
    TYPE_TASK_ASSIGNED,
    TYPE_DEADLINE_REMINDER,
    TYPE_BADGE_EARNED,
    TYPE_LEVEL_ACHIEVED,
    TYPE_MENTION_IN_COMMIT,
    TYPE_SYNC_FAILED,
    TYPE_SYNC_STARTED,
    TYPE_SECURITY_ALERT
}