server:
  port: 8081

spring:
  application:
    name: gitdock-auth

  profiles:
    active: docker

  datasource:
    url: jdbc:postgresql://postgres:5432/gitdock_auth
    username: postgres
    password: ***REMOVED***
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret: ***REMOVED***
      expiration: 86400000
      refresh-token:
        expiration: 604800000