server:
  port: 8081
  error:
    include-message: always

spring:
  application:
    name: gitdock-auth

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23li2o16E8oJxp6jUY
            client-secret: ***REMOVED***
            redirect-uri: "http://localhost:5173/oauth/callback/github"

  # --- CORRECTION ICI : datasource doit avoir 2 espaces de décalage ---
  datasource:
    url: jdbc:postgresql://localhost:5432/gitdock_auth_db
    username: sa
    password: sa
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ***REMOVED***
    password: ***REMOVED***
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

application:
  security:
    jwt:
      secret: ***REMOVED***
      expiration: 86400000
      refresh-token:
        expiration: 604800000
    activation:
      token:
        expiration: 24
  mail:
    activation-url: http://localhost:5173/activate
    reset-password-url: http://localhost:5173/reset-password
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    root: INFO
    edu.ehei.gitdock.gitdockauth: DEBUG
    org.hibernate.tool.schema: DEBUG
    org.springframework.security: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method