server:
  port: 8761

spring:
  application:
    name: gitdock-discovery

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000
    wait-time-in-ms-when-sync-empty: 0